In [ ]:
import numpy as np
import pandas as pd
import csv
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, RepeatVector, Dense
from tensorflow.keras.layers import Reshape
from sklearn.preprocessing import MinMaxScaler

##Peaks Normalization and Log Transformation

In [ ]:
data = []
with open('CrestFactor.csv') as f:
    reader = csv.reader(f)
    next(reader) # skip header
    for row in reader:
        float_row = []
        for x in row[1:]:
            if x == '':
                float_row.append(np.nan)
            else:
                float_row.append(float(x))
        data.append(float_row)

# Replace NaN with 0
data = [np.nan_to_num(x) for x in data]

data=pd.DataFrame(data)

data = data.iloc[91:]
timesteps = 30
n_features = data.shape[1]

In [ ]:
data

0         1         2         3         4         5         6   \
91   2.63469  4.062637  3.129854  4.609137  3.400028  3.178541  3.277437   
92   3.23238  4.078335  7.042780  2.701289  2.655218  2.400014  3.628568   
93   3.03576  4.810912  4.882066  2.596176  2.533021  2.524444  4.248105   
94   3.29761  3.189906  2.945253  2.087754  3.301413  1.889706  3.933348   
95   2.90987  4.485154  3.041485  2.553184  2.612140  2.383652  3.968591   
96   2.86368  3.719087  6.612660  2.638301  2.869519  2.312029  4.383785   
97   4.10185  4.826245  3.330945  2.588093  3.421568  2.400348  4.195410   
98   5.03276  5.343038  6.252811  3.203273  2.773179  4.896499  3.477735   
99   3.09773  3.994526  5.608631  2.984639  3.475719  2.932489  4.005264   
100  2.97183  4.022532  3.628204  1.829227  3.635316  2.109542  2.781441   
101  3.16903  4.152536  5.283985  2.836685  3.258756  2.172708  5.818206   
102  3.10598  4.261526  3.753625  2.911577  3.048107  2.217196  2.771815   
103  3.58805  5.616037  3.618155  2.983855  2.993425  2.138939  2.824765   
104  2.87144  4.497545  5.416764  2.385735  2.741594  2.625767  2.847386   
105  3.13695  3.849488  3.254154  2.481434  2.702853  1.911206  4.653253   
106  3.02256  3.918923  7.408653  3.699954  2.768941  2.251774  4.695032   
107  3.12986  3.261094  5.430862  3.709881  2.670214  2.215141  3.832066   
108  2.73961  4.551932  5.283183  2.933837  3.056496  2.032451  3.351637   
109  3.01889  4.588178  3.436833  2.766410  2.743929  2.265768  4.557664   
110  4.67044  5.892801  2.888782  2.940134  3.085947  2.842087  3.217671   
111  3.06238  4.391883  4.790584  2.672401  3.106201  2.471920  3.638456   
112  2.68976  3.063001  3.284295  2.550634  2.909167  2.870515  2.948894   
113  2.96752  3.427723  5.142579  3.168435  2.925527  2.882172  3.522696   
114  2.91100  5.346841  3.615679  2.268171  2.636649  2.619952  3.026508   
115  3.44720  3.665592  4.204558  2.410078  2.816336  2.149871  3.175934   
116  5.21820  6.522999  3.293842  3.208757  2.728350  2.205509  2.753030   
117  3.66436  3.885828  4.651327  2.712773  3.033157  2.231556  3.529247   
118  3.63460  6.651065  4.016162  3.075069  3.135827  2.686252  0.000000   
119  5.86073  4.790698  2.773870  2.650354  2.774529  2.641721  0.000000   
120  2.67534  3.651369  5.923746  0.000000  0.000000  0.000000  0.000000   

           7         8         9         10  
91   2.873765  2.479360  2.627003  2.917039  
92   3.553896  2.173840  3.197476  3.343181  
93   2.962326  2.775282  3.781715  3.234808  
94   3.393899  2.747097  4.164268  3.000906  
95   3.508693  3.841308  2.683541  2.906957  
96   3.050037  2.950206  2.508664  2.461728  
97   2.644479  3.606444  2.992065  3.111706  
98   3.404237  2.914931  3.365790  2.738528  
99   3.464688  3.356123  3.345502  3.068255  
100  2.704160  2.429076  3.209185  3.446112  
101  2.660786  2.430142  2.883501  2.953736  
102  2.864140  2.945669  3.911164  2.633384  
103  3.551484  2.770592  2.790100  2.660711  
104  2.657926  3.183940  2.735678  2.821371  
105  3.045280  2.776863  2.428481  3.093465  
106  3.371265  3.098504  3.308677  3.090902  
107  2.780782  2.781189  3.837144  3.097755  
108  2.855516  2.602831  4.630186  2.920844  
109  2.617030  3.202961  2.917623  2.828609  
110  2.475964  2.683552  6.749239  3.303933  
111  2.503402  2.473325  3.109962  2.447902  
112  2.913439  2.689282  2.817345  2.981381  
113  2.745999  2.446629  2.688749  3.210787  
114  2.882916  2.734413  3.637954  2.705390  
115  2.949784  2.397437  2.806638  4.298238  
116  2.792126  3.422465  2.327995  2.944939  
117  2.823454  2.961317  4.546049  3.380741  
118  0.000000  0.000000  6.001610  2.956850  
119  0.000000  0.000000  2.604662  3.392571  
120  0.000000  0.000000  0.000000  0.000000

In [ ]:
inputs = Input(shape=(timesteps, 1))
x = LSTM(30)(inputs)
# x = Dense(10)(x)
# x = Dense(15)(x)
encoded = Dense(1)(x)

# decoded = Dense(16)(encoded)
# decoded = Dense(32)(decoded)
# decoded = Dense(61)(decoded)
# decoded = Reshape((61, 1))(decoded)
# decoded = LSTM(1, return_sequences=True)(decoded)
decoded = Dense(timesteps)(encoded)
decoded = Reshape((timesteps, 1))(decoded)
decoded = LSTM(30, return_sequences=True)(decoded)
# decoded = Dense(10)(decoded)
# decoded = Dense(15)(decoded)
decoded = Dense(1)(decoded)

latent_space_model = Model(inputs, encoded)
autoencoder = Model(inputs, decoded)
autoencoder.compile(optimizer='adam', loss='mae')


In [ ]:
autoencoder.summary()

Model: "model_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 30, 1)]           0         
                                                                 
 lstm_12 (LSTM)              (None, 30)                3840      
                                                                 
 dense_34 (Dense)            (None, 1)                 31        
                                                                 
 dense_35 (Dense)            (None, 30)                60        
                                                                 
 reshape_6 (Reshape)         (None, 30, 1)             0         
                                                                 
 lstm_13 (LSTM)              (None, 30, 30)            3840      
                                                                 
 dense_36 (Dense)            (None, 30, 1)             31 

In [ ]:
for i in range(n_features):
    print(f'Training on column: {i+1}/{n_features}')
    x_train = data.iloc[:, i].values.reshape(-1, timesteps, 1)

    autoencoder.fit(x_train, x_train, epochs=40, batch_size=8,verbose=0)

# Save model weights
autoencoder.save_weights('autoencoder_weights.h5')

Training on column: 1/11
Training on column: 2/11
Training on column: 3/11
Training on column: 4/11
Training on column: 5/11
Training on column: 6/11
Training on column: 7/11
Training on column: 8/11
Training on column: 9/11
Training on column: 10/11
Training on column: 11/11


In [ ]:
def predict_sequence_and_latent_space(input_sequence):
    input_sequence = np.array(input_sequence)
    input_sequence = input_sequence.reshape(1, -1, 1)
    print(input_sequence.shape)
    predicted_sequence = autoencoder.predict(input_sequence)
    latent_space_output = latent_space_model.predict(input_sequence)
    return predicted_sequence.reshape(-1), latent_space_output[0][0]

column_to_predict = 0
input_sequence = data.iloc[:, column_to_predict].values.tolist()
predictions, latent_space_output = predict_sequence_and_latent_space(input_sequence)

print("Original Sequence:")
print(input_sequence)

print("Predicted Sequence:")
print(predictions)

print("Latent Space Output:")
print(latent_space_output)

(1, 30, 1)
1/1 [==============================] - 0s 34ms/step
Original Sequence:
[2.63469, 3.23238, 3.03576, 3.29761, 2.90987, 2.86368, 4.10185, 5.03276, 3.09773, 2.97183, 3.16903, 3.10598, 3.58805, 2.87144, 3.13695, 3.02256, 3.12986, 2.73961, 3.01889, 4.67044, 3.06238, 2.68976, 2.96752, 2.911, 3.4472, 5.2182, 3.66436, 3.6346, 5.86073, 2.67534]
Predicted Sequence:
[2.8639705 3.3132727 3.1705136 2.99937   2.9033399 2.9292169 3.027222
 3.1219194 3.3274884 3.1514394 2.935743  2.9115427 2.7028275 2.9562721
 3.020638  3.064098  3.143869  2.9832447 2.959277  3.2803388 2.6832507
 2.7955947 2.7903392 2.8811479 2.943343  2.859746  3.0973077 3.1384845
 2.7583277 2.819826 ]
Latent Space Output:
11.878486


In [ ]:
import pandas as pd

# Convert the predicted sequence back to a DataFrame
predictions_df = pd.DataFrame(predictions, columns=['Predicted Sequence'])

# Get the original DataFrame
original_df = pd.DataFrame(input_sequence, columns = ['Original Sequence'])

# Get the column to predict (column_to_predict) and the corresponding column name
# column_name = original_df.columns[column_to_predict]

# Append the predicted sequence to the original DataFrame
original_df['Predicted Sequence'] = predictions_df

# Save the DataFrame to a CSV file
original_df.to_csv('predicted_sequences.csv', index=False)

print("Original Sequence and Predicted Sequence saved to 'predicted_sequences.csv'")


Original Sequence and Predicted Sequence saved to 'predicted_sequences.csv'


In [ ]:
num_columns = 11  # Total number of columns in your data

def predict_and_get_latent_output(input_sequence, column_idx):
    input_sequence = np.array(input_sequence)
    input_sequence = input_sequence.reshape(1, -1, 1)
    predicted_sequence = autoencoder.predict(input_sequence)
    latent_space_output = latent_space_model.predict(input_sequence)
    return predicted_sequence.reshape(-1), latent_space_output.reshape(-1)

# Create an array to store the latent_space_op values for each column
latent_space_op_array = []

# Loop over each column
for column_idx in range(num_columns):
    input_sequence = data.iloc[:, column_idx].values.tolist()
    predictions, latent_space_output = predict_and_get_latent_output(input_sequence, column_idx)
    latent_space_op_array.append(latent_space_output)

print(latent_space_op_array)

1/1 [==============================] - 0s 22ms/step
[array([11.878486], dtype=float32), array([11.8795595], dtype=float32), array([11.875491], dtype=float32), array([11.865106], dtype=float32), array([11.865122], dtype=float32), array([11.865057], dtype=float32), array([11.86418], dtype=float32), array([11.864109], dtype=float32), array([11.864088], dtype=float32), array([11.86503], dtype=float32), array([11.865132], dtype=float32)]


In [ ]:
latent_space_op_array

[array([11.878486], dtype=float32),
 array([11.8795595], dtype=float32),
 array([11.875491], dtype=float32),
 array([11.865106], dtype=float32),
 array([11.865122], dtype=float32),
 array([11.865057], dtype=float32),
 array([11.86418], dtype=float32),
 array([11.864109], dtype=float32),
 array([11.864088], dtype=float32),
 array([11.86503], dtype=float32),
 array([11.865132], dtype=float32)]

Data saved to output_data.csv


In [ ]:
data = [['Latent Space Output for each column:']]
for item in latent_space_op_array:
    data.append([item[0]])

# Write data to CSV file
csv_filename = 'latent_space_output.csv'
with open(csv_filename, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(data)
